apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: bmh-secret-1
  namespace: cwl-site1
data:
  username: cm9vdAo=
  password: cG9vbDJkcmFjCg==
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: bmh-secret-2
  namespace: cwl-site1
data:
  username: cm9vdAo=
  password: cG9vbDJkcmFjCg==
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: bmh-secret-3
  namespace: cwl-site1
data:
  username: cm9vdAo=
  password: cG9vbDJkcmFjCg==
---
apiVersion: v1
data:
  .dockerconfigjson: <pull-secret>
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: cwl-site1
type: kubernetes.io/dockerconfigjson
