apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "ztplab"
  namespace: "ztplab"
spec:
  baseDomain: "labopool6.jor.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.14.27-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDikFJUEHrienq0oIzOIFPgBARssBwVgNTKU7Vhe37lMTYnCcu3GNNdryE/ZXBzD4Q1lEAWf1nAUM8zbndsgtrx7uups/eKAgv0FiaSplFS3nNI9Wtdc0Zg0ynO2NUhx505vlV/4nGYAolj3hqF3QtbVFLR83S9A8DdlUEufA/PLLe0FmITu4qHMDAmuTwABPkdi8MdAkyBQxop+9mnsC2BMabRtnxIZa3tADYYUF1RGjTgCFmntEdVff2w3eakNsYo0WRxEFgBoz5Oco0mXOEA/imur5TE+PXmZGtyvyFLEVQoHJin+sHfAmv70pUfBXh/aEgEtES3Y2zaMtflt6kBghCJC1plxZWBhv32SX/Y2rj/rXuBZFlYp6pRKtCxzraFTbl2z5ORSgJpIvXQvb8tPdR9se/KEixiGjV/duLetwvNXDRenXpJCqhwR1sIMpcPdqkgXI1KvQKcx4S1SsTzHuT0l33gyDe+HPeqMGmoFaJIsybYG2zSznELnuYlFYEbeHB5tWyZKb82habRbwAO9j4jEyaEDvfM6d9f+p23L6DhATOMdARZHNALMaMPNNzrKOZg4lL2ygH+hysdPAjhJg76iWjqqJVrluF03RZwTcuXsdbFX9pVYXoZwYkB4bCYWv4aVkskVjujgzxQXgZ2yRDSiII2Jg2gnfmHr9mHXw=="
  clusters:
  - clusterName: "ztplab"
    # - NodeTuning is needed for 4.13 and later, not for 4.12 and earlier
    installConfigOverrides:  "{\"capabilities\":{\"baselineCapabilitySet\": \"None\", \"additionalEnabledCapabilities\": [ \"marketplace\", \"NodeTuning\" ] }}"    
    networkType: "OVNKubernetes"
    clusterLabels:
      cluster: ztplab
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 10.1.198.160/28
    # For 3-node and standard clusters with static IPs, the API and Ingress IPs must be configured here
    serviceNetwork:
      - 172.30.0.0/16
    additionalNTPSources:
      - 108.61.73.243
      # - 1111:2222:3333:4444::2
    # Optionally; This can be used to override the KlusterletAddonConfig that is created for this cluster:
    #crTemplates:
    #  KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    # Optionally; This can be used to to configure desired BIOS setting on all nodes in this cluster:
    #biosConfigRef:
    #  filePath: "example-hw.profile"
################################################################
    nodes:
      - hostName: "master1.ztplab.labopool6.jor.com"
        role: "master"
        bmcAddress: "redfish-virtualmedia://10.1.196.66:9000/redfish/v1/Systems/1"
        bmcCredentialsName:
          name: "bmh-secret-1"
        bootMACAddress: "b4:96:91:1d:7c:ae"
        bootMode: "UEFISecureBoot"  
        # Use UEFISecureBoot to enable secure boot for this node
        # bootMode: "UEFI"
        nodeLabels:
          cluster.ocs.openshift.io/openshift-storage: "true"
        rootDeviceHints:
          deviceName: "/dev/sda"
# As per: https://docs.openshift.com/container-platform/4.11/scalability_and_performance/cnf-talm-for-cluster-upgrades.html#cnf-about-topology-aware-lifecycle-manager-config_cnf-topology-aware-lifecycle-manager
        #diskPartition:
        #  - device: /dev/sda
        #    partitions:
        #    - mount_point: /var/recovery
        #      size: 51200
        #      start: 800000
        nodeNetwork:
          interfaces:
            - name: "enp5s0f0"
              macAddress: "b4:96:91:1d:7c:ac"
            - name: "enp5s0f1"
              macAddress: "b4:96:91:1d:7c:ae"
          config:
            interfaces:
              - name: enp5s0f0.310
                type: vlan
                state: up
                vlan:
                  base-iface: enp5s0f0
                  id: 310
                ipv4:
                  address:
                  - ip: 10.1.198.169
                    prefix-length: 28
                  enabled: true
                ipv6:
                  enabled: false
            dns-resolver:
              config:
                server:
                  - 10.1.196.66
            routes:
              config:
                - destination: 0.0.0.0/0
                  next-hop-interface: enp5s0f0.310
                  next-hop-address: 10.1.198.174
