apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "ztplab"
  namespace: "ztplab"
spec:
  baseDomain: "labopool6.jor.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.14.34-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCqV60mnfadiSX4JG2763D4Zu6aqu35SAhSMSsVin2oVM314bkNnNR1HklqEfSzDrKfxHRTBhwx3yBuEy1sYRj1/JDvJxcMvFe9Qzgw++yqsIXIY39zpkADzoSnpcYx2QaUpkwLHGlaPknZvvfR+NnKY8q5m53vZikSOSnPmTNtHyCBFC5U/36q5S9pkHhBM/+fMh3bnfUEk6A6111CWTrR67NyBmP/1XLswWUltc7mgj2muCAd6nfr4JYmHkNh3rMJrZEkTE8M5PI2CtOpeaYS8oaTudCccztat1GUEZ8cX88cqQ2WrtRl/ssrfozKG/0eV25BAIZtbwmSKEPw05OeUQibd9NI2HOfzZzmvQf7IuYW62AeCzgUDyschcG9KFBKWk7MNtBtd0A9PbYhB3Yz+uNamIcXfNFsmWr9S6o8m9FM9ZFfRwCB2U7mJzc5Ct1kcGZkXdHMbZhvZqgcIWVZptUzvdsogdnpyFRrXWcIuyZ+rPuT3B91kqafPdHNXLPCcIE+d5D2DabU0MdKp/98MFsLX7zuGrvsQZxJV5Cqtfy5PMqRfOL4wjB1zhCVgffszN2Az5WmELjIc5LIsWHG1GV34SqH1dEjjmINrKY26qLMx/XWZLozpbYGOVjZfdL3UOUGa496X8odyBc5IMmCeyVa23OgxOem9sznT0V5lw=="
  clusters:
  - clusterName: "ztplab"
    networkType: "OVNKubernetes"
    holdInstallation: false
    clusterLabels:
      cluster: "ztplab"
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 10.1.198.160/28
    # For 3-node and standard clusters with static IPs, the API and Ingress IPs must be configured here
    apiVIP: 10.1.198.173
    apiVIPs:
      - 10.1.198.173
    ingressVIP:  10.1.198.172
    ingressVIPs:
      - 10.1.198.172
    serviceNetwork:
      - 172.30.0.0/16
    additionalNTPSources:
      - 108.61.73.243
      # - 1111:2222:3333:4444::2
    # Optionally; This can be used to override the KlusterletAddonConfig that is created for this cluster:
    #crTemplates:
    #  KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    # Optionally; This can be used to to configure desired BIOS setting on all nodes in this cluster:
    #biosConfigRef:
    #  filePath: "example-hw.profile"
################################################################
    nodes:
      - hostName: "master1.ztplab.labopool6"
        role: "master"
        bmcAddress: "redfish-virtualmedia://10.1.196.66:9000/redfish/v1/Systems/1"
        bmcCredentialsName:
          name: "bmh-secret-1"
        bootMACAddress: "b4:96:91:1d:7c:ae"
        bootMode: "UEFISecureBoot"  
        # Use UEFISecureBoot to enable secure boot for this node
        # bootMode: "UEFI"
        nodeLabels:
          cluster.ocs.openshift.io/openshift-storage: "true"
        rootDeviceHints:
          deviceName: "/dev/sda"
# As per: https://docs.openshift.com/container-platform/4.11/scalability_and_performance/cnf-talm-for-cluster-upgrades.html#cnf-about-topology-aware-lifecycle-manager-config_cnf-topology-aware-lifecycle-manager
        #diskPartition:
        #  - device: /dev/sda
        #    partitions:
        #    - mount_point: /var/recovery
        #      size: 51200
        #      start: 800000
        nodeNetwork:
          interfaces:
            - name: "enp5s0f0"
              macAddress: "b4:96:91:1d:7c:ac"
            - name: "enp5s0f1"
              macAddress: "b4:96:91:1d:7c:ae"
          config:
            interfaces:
              - name: enp5s0f1.310
                type: vlan
                state: up
                vlan:
                  base-iface: enp5s0f1
                  id: 310
                ipv4:
                  address:
                  - ip: 10.1.198.169
                    prefix-length: 28
                  enabled: true
                ipv6:
                  enabled: false
              - name: enp5s0f0
                type: ethernet
                state: down
                ipv4:
                  enabled: false                    
              - name: enp5s0f1
                type: ethernet
                state: up
                ipv4:
                  enabled: false                    
            dns-resolver:
              config:
                server:
                  - 10.1.196.66
            routes:
              config:
                - destination: 0.0.0.0/0
                  next-hop-interface: enp5s0f1.310
                  next-hop-address: 10.1.198.174
############################################################
      - hostName: "master2.ztplab.labopool6"
        role: "master"
        bmcAddress: "redfish-virtualmedia://10.1.196.66:9001/redfish/v1/Systems/1"
        bmcCredentialsName:
          name: "bmh-secret-2"
        bootMACAddress: "b4:96:91:1d:7f:b6"
        bootMode: "UEFISecureBoot"  
        # Use UEFISecureBoot to enable secure boot for this node
        # bootMode: "UEFI"
        nodeLabels:
          cluster.ocs.openshift.io/openshift-storage: "true"
        rootDeviceHints:
          deviceName: "/dev/sda"
# As per: https://docs.openshift.com/container-platform/4.11/scalability_and_performance/cnf-talm-for-cluster-upgrades.html#cnf-about-topology-aware-lifecycle-manager-config_cnf-topology-aware-lifecycle-manager
        #diskPartition:
        #  - device: /dev/sda
        #    partitions:
        #    - mount_point: /var/recovery
        #      size: 51200
        #      start: 800000
        nodeNetwork:
          interfaces:
            - name: "enp5s0f0"
              macAddress: "b4:96:91:1d:7f:b4"
            - name: "enp5s0f1"
              macAddress: "b4:96:91:1d:7f:b6"
          config:
            interfaces:
              - name: enp5s0f1.310
                type: vlan
                state: up
                vlan:
                  base-iface: enp5s0f1
                  id: 310
                ipv4:
                  address:
                  - ip: 10.1.198.170
                    prefix-length: 28
                  enabled: true
                ipv6:
                  enabled: false
              - name: enp5s0f0
                type: ethernet
                state: down
                ipv4:
                  enabled: false                    
              - name: enp5s0f1
                type: ethernet
                state: up
                ipv4:
                  enabled: false                    
            dns-resolver:
              config:
                server:
                  - 10.1.196.66
            routes:
              config:
                - destination: 0.0.0.0/0
                  next-hop-interface: enp5s0f1.310
                  next-hop-address: 10.1.198.174
############################################################
      - hostName: "master3.ztplab.labopool6"
        role: "master"
        bmcAddress: "redfish-virtualmedia://10.1.196.66:9002/redfish/v1/Systems/1"
        bmcCredentialsName:
          name: "bmh-secret-3"
        bootMACAddress: "b4:96:91:1d:7f:32" 
        bootMode: "UEFISecureBoot"  
        # Use UEFISecureBoot to enable secure boot for this node
        # bootMode: "UEFI"
        nodeLabels:
          cluster.ocs.openshift.io/openshift-storage: "true"
        rootDeviceHints:
          deviceName: "/dev/sda"
# As per: https://docs.openshift.com/container-platform/4.11/scalability_and_performance/cnf-talm-for-cluster-upgrades.html#cnf-about-topology-aware-lifecycle-manager-config_cnf-topology-aware-lifecycle-manager
        #diskPartition:
        #  - device: /dev/sda
        #    partitions:
        #    - mount_point: /var/recovery
        #      size: 51200
        #      start: 800000
        nodeNetwork:
          interfaces:
            - name: "enp5s0f0"
              macAddress: "b4:96:91:1d:7f:30"
            - name: "enp5s0f1"
              macAddress: "b4:96:91:1d:7f:32"
          config:
            interfaces:
              - name: enp5s0f1.310
                type: vlan
                state: up
                vlan:
                  base-iface: enp5s0f1
                  id: 310
                ipv4:
                  address:
                  - ip: 10.1.198.171
                    prefix-length: 28
                  enabled: true
                ipv6:
                  enabled: false
              - name: enp5s0f0
                type: ethernet
                state: down
                ipv4:
                  enabled: false                    
              - name: enp5s0f1
                type: ethernet
                state: up
                ipv4:
                  enabled: false                    
            dns-resolver:
              config:
                server:
                  - 10.1.196.66
            routes:
              config:
                - destination: 0.0.0.0/0
                  next-hop-interface: enp5s0f1.310
                  next-hop-address: 10.1.198.174
############################################################
      - hostName: "worker1.ztplab.labopool6"
        role: "worker"
        bmcAddress: "redfish-virtualmedia://10.1.196.66:9003/redfish/v1/Systems/1"
        bmcCredentialsName:
          name: "bmh-secret-4"
        bootMACAddress: "b4:96:91:1d:7f:de"
        bootMode: "UEFISecureBoot"
        # Use UEFISecureBoot to enable secure boot for this node
        # bootMode: "UEFI"
        nodeLabels:
          cluster.ocs.openshift.io/openshift-storage: "true"
        rootDeviceHints:
          deviceName: "/dev/sda"
# As per: https://docs.openshift.com/container-platform/4.11/scalability_and_performance/cnf-talm-for-cluster-upgrades.html#cnf-about-topology-aware-lifecycle-manager-config_cnf-topology-aware-lifecycle-manager
        #diskPartition:
        #  - device: /dev/sda
        #    partitions:
        #    - mount_point: /var/recovery
        #      size: 51200
        #      start: 800000
        nodeNetwork:
          interfaces:
            - name: "enp5s0f0"
              macAddress: "b4:96:91:1d:7f:dc"
            - name: "enp5s0f1"
              macAddress: "b4:96:91:1d:7f:de"
          config:
            interfaces:
              - name: enp5s0f1.310
                type: vlan
                state: up
                vlan:
                  base-iface: enp5s0f1
                  id: 310
                ipv4:
                  address:
                  - ip: 10.1.198.168
                    prefix-length: 28
                  enabled: true
                ipv6:
                  enabled: false
              - name: enp5s0f0
                type: ethernet
                state: down
                ipv4:
                  enabled: false                    
              - name: enp5s0f1
                type: ethernet
                state: up
                ipv4:
                  enabled: false                    
            dns-resolver:
              config:
                server:
                  - 10.1.196.66
            routes:
              config:
                - destination: 0.0.0.0/0
                  next-hop-interface: enp5s0f1.310
                  next-hop-address: 10.1.198.174
############################################################
      - hostName: "worker2.ztplab.labopool6"
        role: "worker"
        bmcAddress: "redfish-virtualmedia://10.1.196.66:9004/redfish/v1/Systems/1"
        bmcCredentialsName:
          name: "bmh-secret-5"
        bootMACAddress: "b4:96:91:1d:7f:be"
        bootMode: "UEFISecureBoot"
        # Use UEFISecureBoot to enable secure boot for this node
        # bootMode: "UEFI"
        nodeLabels:
          cluster.ocs.openshift.io/openshift-storage: "true"
        rootDeviceHints:
          deviceName: "/dev/sda"
# As per: https://docs.openshift.com/container-platform/4.11/scalability_and_performance/cnf-talm-for-cluster-upgrades.html#cnf-about-topology-aware-lifecycle-manager-config_cnf-topology-aware-lifecycle-manager
        #diskPartition:
        #  - device: /dev/sda
        #    partitions:
        #    - mount_point: /var/recovery
        #      size: 51200
        #      start: 800000
        nodeNetwork:
          interfaces:
            - name: "enp5s0f0"
              macAddress: "b4:96:91:1d:7f:bc"
            - name: "enp5s0f1"
              macAddress: "b4:96:91:1d:7f:be"
          config:
            interfaces:
              - name: enp5s0f1.310
                type: vlan
                state: up
                vlan:
                  base-iface: enp5s0f1
                  id: 310
                ipv4:
                  address:
                  - ip: 10.1.198.167
                    prefix-length: 28
                  enabled: true
                ipv6:
                  enabled: false
              - name: enp5s0f0
                type: ethernet
                state: down
                ipv4:
                  enabled: false                    
              - name: enp5s0f1
                type: ethernet
                state: up
                ipv4:
                  enabled: false                    
            dns-resolver:
              config:
                server:
                  - 10.1.196.66
            routes:
              config:
                - destination: 0.0.0.0/0
                  next-hop-interface: enp5s0f1.310
                  next-hop-address: 10.1.198.174                  
